version: '3'
services:
  backend:
    build: ./backend/
    ports:
     - "5000:5000"
  frontend:
    build:
      context: ./frontend/
      args:
        - backend_endpoint=http://localhost:5000
    ports:
     - "80:80"