version: '3'
services:
  backend:
    depends_on:
      - redis
    build: ./backend/
    ports:
     - "5000:5000"
  frontend:
    build:
      context: ./frontend/
      args:
        - backend_endpoint=http://localhost:5000
    ports:
     - "80:80"
  redis:
    image: "redis:latest"
    volumes:
      - $HOME/data:/data